import type { HealthPlanSubmenuPageData, HealthPlanSubmenuPath } from "../../../../_types/menu/submenu/health-plans/health-plans";

export const healthPlanSubmenuPages = {
  "health-plans/integrative-health-solutions": {
    kind: "products",
    path: "health-plans/integrative-health-solutions",
    title: "Integrative Health Solutions",
    description: "WholeHealth Living makes it easier to offer our Integrative Health Solutions to alleviate pain and support the health and well-being of your members.",
    heroImage: "/images/iStock-1265315809.jpg",
    sidebarImage: "/images/iStock-1270104024-1075x1613-1.png",
    lead: "WholeHealth Living's Integrative Health Solutions emphasize the delivery of high-quality care, with appropriate cost containment to improve clinical outcomes, create savings, and enhance member satisfaction.",
    summary: "Our Integrative Health Solutions are custom designed for each health plan by combining our four core services and seven specialties.",
    services: [
      {
        label: "Practitioner Network Management",
        text: "WholeHealth Living will identify, build, credential, and manage a network of qualified licensed integrative health practitioners to deliver care to your members.",
        subitems: ["Recruitment and Contracting", "Credentialing", "Practitioner Engagement and Retention"],
      },
      {
        label: "Provider Engagement",
        text: "WholeHealth Living serves as the connector between the broader medical community and the integrative health practitioner community to deliver holistic care to your members.",
      },
      {
        label: "Utilization Management",
        text: "The WholeHealth Living Utilization Management approach delivers clinically appropriate care grounded in evidence based best practices, utilizing data analytics, practitioner education and engagement.",
      },
      {
        label: "Claims Processing Services",
        text: "As a part of the WholeHealth Living suite of services, we have full claims processing capabilities that include claims repricing and/or claims payment.",
      },
    ],
    specialtiesIntro:
      "WholeHealth Living provides access to a full range of integrative health specialties. Our integrative health practitioners support an evidence based and nonpharmacological pain management strategy that can attract and retain members.",
    specialties: [
      { label: "Acupuncture", href: "/health-plans/acupuncture", text: "involves the stimulation of specific points on the body, typically utilizing very thin sterilized needles, inserted through the skin." },
      { label: "Chiropractic Care", href: "/health-plans/chiropractic", text: "is a natural treatment that addresses joint pain, backaches, headaches, and other symptoms that affect quality of life." },
      { label: "Massage Therapy", href: "/health-plans/massage-therapy", text: "offers a natural approach that may enhance a person's health and well-being." },
      { label: "Naturopathy", href: "/health-plans/naturopathy", text: "typically manages acute and chronic conditions, performs wellness exams and screening tests, orders labs and imaging as necessary, and refers to specialists as needed." },
      { label: "Occupational Therapy", href: "/health-plans/occupational-therapy", text: "provides customized interventions to improve a person's ability to perform daily activities in their homes, workplaces, and communities." },
      { label: "Physical Therapy", href: "/health-plans/physical-therapy", text: "focuses on improving mobility, decreasing pain, and avoiding surgery." },
      { label: "Speech Therapy", href: "/health-plans/speech-therapy", text: "treats a variety of speech, language, social communication, cognitive-communication, and swallowing disorders in children and adults." },
    ],
    footnote: "1. Perceptions of Integrative Health Services Among The General Population, Tivity Health Consumer Research, December 2022.",
  },
  "health-plans/acupuncture": {
    kind: "specialty",
    path: "health-plans/acupuncture",
    title: "Acupuncture",
    description: "Acupuncture involves the stimulation of specific points on the body, typically utilizing very thin sterilized needles, inserted through the skin.",
    heroClass: "heroAcupuncture",
    image: "/images/wholehealth_living_acupuncture.webp",
    heading: "Offer Acupuncture as a Benefit",
    benefits: [
      { label: "First-line pain management", text: "When you offer acupuncture to your members, they have access to a first-line of care to manage pain before high-cost invasive procedures like ER visits, MRIs, and surgeries occur, reducing overall spend.", marker: "1" },
      { label: "Opioid alternative", text: "Acupuncture provides an alternative solution to managing pain and may reduce the need for prescription opioids. Members can remain active and socially connected.", marker: "2" },
      { label: "Member retention", text: "An acupuncture benefit can attract and retain members looking for an alternative medicine option.", marker: "3" },
      { label: "Health enhancement", text: "Acupuncture may impact the overall health and well-being of your members.", marker: "3" },
    ],
    footnotes: [
      "1. Andronis, L., Kinghorn, P., Qiao, S., Whitehurst, D. G., Durrell, S., & McLeod, H. (2017). Cost-Effectiveness of Non-Invasive and Non-Pharmacological Interventions for Low Back Pain.",
      "2. Traditional Chinese Medicine: What You Need To Know. Retrieved from https://www.nccih.nih.gov/health/traditional-chinese-medicine-what-you-need-to-know",
      "3. Tivity Health Consumer Research, September 2019.",
    ],
    quote: "70% of members indicate that offering services like acupuncture would most likely raise their perception of their health plan.",
  },
  "health-plans/chiropractic": {
    kind: "specialty",
    path: "health-plans/chiropractic",
    title: "Chiropractic Care",
    description: "Chiropractic care is a natural treatment that addresses joint pain, backaches, headaches, and other symptoms that affect quality of life.",
    heroClass: "heroChiropractic",
    image: "/images/wholehealth_living_chiropractic_care.webp",
    heading: "Offer Chiropractic Care as a Benefit",
    intro: "Chiropractors focus on the diagnosis, treatment, and prevention of mechanical disorders of the spine and musculoskeletal system, as well as the musculoskeletal effects on the nervous system and general health.",
    benefits: [
      { label: "Reduce out-of-pocket spend", text: "Chiropractic care is less costly for the member than most highly invasive treatments. Members will appreciate the opportunity to reduce their out-of-pocket spend.", marker: "1" },
      { label: "Managing spend", text: "Utilization Management oversight helps control overspend on unnecessary chiropractic visits.", marker: "2" },
      { label: "Pain management", text: "Chiropractic care supports health plan pain management strategy by reducing barriers and encouraging members to utilize chiropractic benefits as a first-line of treatment.", marker: "3" },
      { label: "Reduces medical spend", text: "Research shows that chiropractic benefits can mitigate musculoskeletal pain and may reduce primary care physician visits.", marker: "4" },
    ],
    footnotes: [
      "1. McGowan, J. R., & Suiter, L. (2019). Cost-Efficiency and Effectiveness of Including Doctors of Chiropractic to Offer Treatment Under Medicaid.",
      "2. Medicare Needs Better Controls To Prevent Fraud, Waste, And Abuse Related To Chiropractic Services. U.S. Department of Health and Human Services, February 2018.",
      "3. Paige NM, Miake-Lye IM, Booth MS, et al. Association of Spinal Manipulative Therapy With Clinical Benefit and Harm for Acute Low Back Pain.",
      "4. Davis, M. A., Yakusheva, O., Gottlieb, D. J., & Bynum, J. P. (2015). Regional Supply of Chiropractic Care and Visits to Primary Care Physicians for Back and Neck Pain.",
    ],
    quote: "A chiropractic benefit may support health plan pain management strategy by reducing barriers to receive care.",
  },
  "health-plans/massage-therapy": {
    kind: "specialty",
    path: "health-plans/massage-therapy",
    title: "Massage Therapy",
    description: "Massage therapy offers a natural approach that may enhance a person's health and well-being.",
    heroClass: "heroMassage",
    image: "/images/wholehealth_living_massage_therapy.webp",
    heading: "Offer Massage Therapy as a Benefit",
    intro: "Massage therapy offers benefits to members who seek to reduce stress, relieve anxiety, relax muscle tension, or as a nonpharmacologic alternative for pain management for musculoskeletal conditions.",
    benefits: [
      { label: "Market differentiation", text: "A massage therapy benefit can differentiate your offering in the marketplace, especially for members who may not be comfortable with acupuncture or chiropractic care." },
      { label: "Approved by CMS", text: "Massage therapy has been approved by CMS and is included in the 2021 call letter.", marker: "1" },
      { label: "Complements pain management", text: "Massage also complements a pain management strategy as a low-risk integrative health solution." },
    ],
    footnotes: ["1. https://www.cms.gov/files/document/2021-announcement.pdf"],
  },
  "health-plans/naturopathy": {
    kind: "specialty",
    path: "health-plans/naturopathy",
    title: "Naturopathy",
    description: "Naturopathic doctors typically manage acute and chronic conditions, perform wellness exams and screening tests, order labs and imaging as necessary and refer to specialists as needed. Licensing requirements vary by state.",
    heroClass: "heroNaturopathy",
    image: "/images/wholehealth_living_naturopathy.webp",
    heading: "Offer Naturopathy as a Benefit",
    benefits: [
      { label: "Offer as an integrative solution", text: "Help your members use natural treatment methods in conjunction with conventional clinical approaches to prevent disease, restore health and promote wellness." },
      { label: "Improve access", text: "Provide a safe and effective option to prevent disease, restore health, and promote wellness." },
      { label: "Empower members", text: "Allow members to take command of their health through a member-focused approach that increases engagement." },
    ],
    quote: "Musculoskeletal disorders continue to be a leading healthcare spend, and our customers are looking for alternative solutions.",
    quoteFootnote: "Dieleman JL, Baral R, Birger M, et al. US Spending on Personal Health Care and Public Health, 1996-2013. Tivity Health Consumer Research, September 2019.",
  },
  "health-plans/occupational-therapy": {
    kind: "specialty",
    path: "health-plans/occupational-therapy",
    title: "Occupational Therapy",
    description: "Occupational Therapy seeks to help people of all ages live life to its fullest by promoting health and by treating people with injury, illness, disability, and other limitations.",
    heroClass: "heroOccupationalTherapy",
    image: "/images/wholehealth_living_occupational_therapy.webp",
    heading: "Offer Occupational Therapy as a Benefit",
    intro: "Occupational therapists provide customized interventions to improve a person's ability to perform daily activities in their homes, their workplaces and their communities.",
    benefits: [
      { label: "Enhance well-being", text: "Help members of all ages live life to its fullest by promoting health and wellness.", marker: "1" },
      { label: "Restore function", text: "Assist members to develop, maintain and restore movement improving their functional ability to perform daily activities." },
      { label: "Focus on everyday tasks", text: "Support members from a holistic perspective, focusing on adapting the environment and or tasks to fit a person's needs." },
    ],
    footnotes: ["1. American Occupational Therapy Association (2015). Standards of Practice for Occupational Therapy. American Journal of Occupational Therapy 69 (Supplement 3)."],
  },
  "health-plans/speech-therapy": {
    kind: "specialty",
    path: "health-plans/speech-therapy",
    title: "Speech Therapy",
    description: "Speech-language pathologists diagnose and treat a variety of speech, language, social communication, cognitive-communication, and swallowing disorders in children and adults.",
    heroClass: "heroSpeechTherapy",
    image: "/images/wholehealth_living_speech_therapy.webp",
    heading: "Offer Speech Therapy as a Benefit",
    benefits: [
      { label: "Timely treatment", text: "Members may benefit from timely and properly treated speech, language, and hearing disorders, and therefore, avoid costly claims in the future due to inappropriate or delayed treatment." },
      { label: "Enhanced quality of life", text: "Members with speech, language, and hearing impairments can improve interpersonal communication, maximize function, and achieve a better quality of life." },
      { label: "Increase personal productivity", text: "Members may decrease time spent on seeking care, resulting in increased productivity at work." },
    ],
    footnotes: ["Why Add Speech, Language, and Hearing Benefits? American Speech-Language-Hearing Association, 2021. Available from https://www.asha.org/public/add-benefits/add/"],
  },
  "health-plans/physical-therapy": {
    kind: "specialty",
    path: "health-plans/physical-therapy",
    title: "Physical Therapy",
    description: "Physical therapists focus on improving mobility, decreasing pain, and avoiding surgery.",
    heroClass: "heroPhysicalTherapy",
    image: "/images/wholehealth_living_physical_therapy.webp",
    heading: "Offer Physical Therapy as a Benefit",
    intro: "Physical therapy is treatment provided by a physical therapist and or physical therapist assistant that helps people improve their movement and physical function, manage pain and other chronic conditions, and recover from or prevent injury and chronic disease.",
    benefits: [
      { label: "Enhance function", text: "Helps members develop, maintain, and restore movement and function." },
      { label: "Pain management", text: "Provide alternative options for managing pain, decreasing the risks of opioid use." },
      { label: "Reduce overall spend", text: "Often helps avoid more costly invasive options like surgeries.", marker: "1" },
    ],
    footnotes: ["1. Initial Treatment Intervention and Average Total Medicare A/B Costs for FFS Beneficiaries with an Incident Low Back Pain Diagnosis in CY 2014. May 2017."],
  },
} satisfies Record<HealthPlanSubmenuPath, HealthPlanSubmenuPageData>;

export function getHealthPlanSubmenuPage(path: string) {
  return healthPlanSubmenuPages[path as HealthPlanSubmenuPath];
}
